name: Build and Push to Nuget

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
 
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
        
    - name: GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
      #with:
      #  useConfigFile: true
      #  additionalArguments: '/showConfig'   
        
    - name: pack
      run: dotnet pack -c Release --version-suffix ${{ steps.gitversion.outputs.nuGetVersion }}
        
    - name: publish
      if: github.event_name != 'pull_request' && github.ref_name == 'master'
      run: |
        dotnet nuget push **/*.nupkg --source 'https://api.nuget.org/v3/index.json' --skip-duplicate -k ${{ secrets.nuget }} --no-symbols 1 
