name: Build and Push to Nuget

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v1
 
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
        
    - name: setup GitVersion
      run: |
        dotnet tool install --global GitVersion.Tool --version 5.*
    
    - name: run GitVersion
      run: |
        dotnet-gitversion
        
    - name: pack
      run: |
        cd lib & dotnet pack -c Release
        
    - name: publish
      if: github.event_name != 'pull_request' && github.ref_name == 'master'
      run: |
        dotnet nuget push **/*.nupkg --source 'https://api.nuget.org/v3/index.json' --skip-duplicate -k ${{ secrets.nuget }} --no-symbols 1 
