name: Build and Push to Nuget

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - name: git checkout
      uses: actions/checkout@v1
 
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
        
    - name: Git Version
      uses: codacy/git-version@2.5.4
      
    - name: get new version
      run: |
        NEW_VERSION=$(docker run --rm -v $(pwd):/repo codacy/git-version)
        echo $NEW_VERSION      
        
    - name: pack
      run: dotnet pack -c Release --version-suffix $version
        
    - name: publish
      if: github.event_name != 'pull_request' && github.ref_name == 'master'
      run: |
        dotnet nuget push **/*.nupkg --source 'https://api.nuget.org/v3/index.json' --skip-duplicate -k ${{ secrets.nuget }} --no-symbols 1 
